USE sqldb;
CREATE TABLE `buytbl` (
`num` INT(10) NOT NULL AUTO_INCREMENT,
`userID` CHAR(8) NOT NULL,
`prodName` CHAR(6) NOT NULL,
`groupName` CHAR(4) NULL DEFAULT NULL,  
`price` INT(10) NOT NULL, 
`amount` SMALLINT(5) NOT NULL,
PRIMARY KEY (`num`) USING BTREE,
INDEX `userID` (`userID`) USING BTREE,
CONSTRAINT `FK_buytbl_sqldb.USERTBL` FOREIGN KEY (`userID`) REFERENCES 
`sqldb`.`usertbl` (`userID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
ENGINE=INNODB 
AUTO_INCREMENT=1
;

